In [2]:
import numpy as np

### Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

Expected Output:

`[0 1 2 3 4 5 6 7 8 9]`

In [4]:
ex1 = np.arange(0,10)
print("Output: \n", ex1)

Output: 
 [0 1 2 3 4 5 6 7 8 9]


### Exercise 2: Convert 1D Array to 2D

Write a code snippet to convert a 1D array to a 2D array with 2 rows.

**Given:**
```python
import numpy as np
arr = np.arange(6)
```

**Expected Output:**
```text
Original Array: [0 1 2 3 4 5] 
Reshaped 2x3 Array: 
[[0 1 2]
 [3 4 5]]
```


In [9]:
orig_arr = np.arange(6)
print('Original Array: ', orig_arr)

reshaped_arr = orig_arr.reshape(2,3)
print('Reshaped Array: \n', reshaped_arr)

Original Array:  [0 1 2 3 4 5]
Reshaped Array: 
 [[0 1 2]
 [3 4 5]]


### Exercise 3: Print Array Attributes

**Instructions**
Print the following attributes of the array:
* The shape of the array.
* The number of array dimensions.
* The size of each element in bytes.

**Given:**
```python
import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
```

**Expected Output:**
```text
The shape of the array is: (4, 2)
The number of dimensions is: 2
The size of each element in bytes is: 2
```

In [15]:
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)
print('The shape of the array is: ', my_array.shape)
print('The number of dimensions is: ', my_array.ndim)
print('The size of each element in bytes is: ', my_array.itemsize)

The shape of the array is:  (4, 2)
The number of dimensions is:  2
The size of each element in bytes is:  2


### Exercise 4: Create a 3×3 NumPy array of all True

**Expected Output:**
```text
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

In [17]:
# truthy_arr = np.full((3,3), True)
truthy_arr = np.ones((3,3), dtype=bool)

print(truthy_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 5: Extract the documentation of NumPy’s arange() function
**Expected Output:**

```python
arange([start,] stop[, step,], dtype=None, *, like=None)
............
```


In [ ]:
print(np.info(np.arange))


arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [25]:
print("Zeros: ", np.zeros(5))
print("Ones: ", np.ones(5))

Zeros:  [0. 0. 0. 0. 0.]
Ones:  [1. 1. 1. 1. 1.]


In [32]:
arr = np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [33]:
py_list = [1, 2, 3, 4, 5]
np_arr = np.array(py_list)
print(np_arr)

[1 2 3 4 5]


In [39]:
arr = np.arange(0,10)
print('Array: ', arr)
print('Memory size in bytes: ', arr.nbytes)

Array:  [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes:  80


In [43]:
arr = np.arange(10)
reversed_arr = arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [49]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
arr = np.arange(1,17).reshape(4,4)
print('First Row: ', arr[0])
print('Last Column: ', arr[:, -1])

First Row:  [1 2 3 4]
Last Column:  [ 4  8 12 16]


In [69]:
sampleArray = np.array([
    [3, 6, 9, 12],
    [15, 18, 21, 24],
    [27, 30, 33, 36],
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])

res = sampleArray[1::2, 0::2]
print(res)

[[15 21]
 [39 45]]


In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h_arr = np.hstack((a,b))
print(h_arr)

[1 2 3 4 5 6]


In [91]:
arr = np.arange(1,17).reshape(4,4)
res_arr = arr[:2, :2]
print(res_arr)

[[1 2]
 [5 6]]


In [98]:
o_arr = np.arange(1,11)
anti_odd_arr = np.where(o_arr % 2 != 0, -1,o_arr)
print('Original Array: ',o_arr)
print('Modified Array: ',anti_odd_arr)

Original Array:  [ 1  2  3  4  5  6  7  8  9 10]
Modified Array:  [-1  2 -1  4 -1  6 -1  8 -1 10]


In [106]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr)
print('Array: ', arr)
print("Indices: ", indices)

Array:  [1 0 2 0 3 0 4]
Indices:  (array([0, 2, 4, 6]),)


In [107]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

common_elements = np.intersect1d(a,b)
print(common_elements)

[2 4 8]


In [108]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Element-wise Sum: ", a+b)
print("Element-wise multiplication: ", a*b)

Element-wise Sum:  [5 7 9]
Element-wise multiplication:  [ 4 10 18]


In [110]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print('Dot Product: ',a @ b)

Dot Product:  32


In [115]:
arr = np.array([10, 20, 30, 100, 200, 300])

print('Mean: ', np.mean(arr))
print('Median: ', np.median(arr))
print('Standard Deviation: ', np.std(arr))

Mean:  110.0
Median:  65.0
Standard Deviation:  107.08252269472673


In [122]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

mask = np.isin(a, b)

# Use the `~` operator to invert the mask (get the opposite)
result = a[~mask]
print(result)

[1 2 3 4]


In [126]:
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print('Normalized Array: ', normalized)

Normalized Array:  [0.   0.25 0.5  0.75 1.  ]


In [132]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

index = np.where(a==b)

print(index)

(array([0, 2]),)


In [151]:
arr = np.arange(15)
exp = arr[(arr >= 5) & (arr <= 10)]
print(exp)

[ 5  6  7  8  9 10]


In [170]:
mat = np.random.rand(6).reshape(3,2)
print(mat)
print(f"Max Value: , {mat.max():.2f}")
print(f"Min Value: , {mat.min():.2f}")

[[0.70484177 0.99356323]
 [0.54983435 0.92937786]
 [0.93629576 0.46406722]]
Max Value: , 0.99
Min Value: , 0.46


In [187]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

# Get the indices that would sort the array by its second column
sorted_indices = sampleArray[:, 1].argsort()

# Use the sorted indices to reorder the rows of the array
sorted_array = sampleArray[sorted_indices]

print("Original array: \n", sampleArray)
print("Sorted array: \n", sorted_array)

Original array: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorted array: 
 [[82 22 12]
 [34 43 73]
 [53 94 66]]


In [199]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumnToAdd = np.array([10, 10, 10])

# Delete the second column (index 1)
# axis=1 specifies that the operation should be on columns
deletedArray = np.delete(sampleArray, 1, axis=1)

# Insert the new column at the second position (index 1)
# axis=1 specifies that we're inserting a column
resultArray = np.insert(deletedArray, 1, newColumnToAdd, axis=1)

print(resultArray)


[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [201]:
arr = np.arange(9).reshape(3, 3)
# The columns are at index 0, 1, 2. We want to rearrange to 0, 2, 1
arr[:, [1,2]] = arr[:, [2,1]]
print(arr)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
arr = np.random.randint(1, 101, 10)
print("Random Integers:", arr)

Random Integers: [ 5  9 33 20 49 53 30 10 20 77]


In [214]:
arr = np.random.randint(1, 101, size=(3,3))
sorted_arr = np.sort(arr, axis=1)
print("Original Array:\n",arr)
print("Row-wise Sorted Array:\n ",sorted_arr)

Original Array:
 [[89 90 64]
 [30 91 80]
 [66 47 33]]
Row-wise Sorted Array:
  [[64 89 90]
 [30 80 91]
 [33 47 66]]


In [219]:
arr = np.arange(10)
print("Original Array: ", arr)

np.random.shuffle(arr)
print("Shuffled Array: ", arr)

Original Array:  [0 1 2 3 4 5 6 7 8 9]
Shuffled Array:  [3 7 0 1 8 2 5 6 9 4]


In [221]:
matrix = np.ones((5,5), dtype=int)
matrix[1:4, 1:4] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
a = np.array([1, 2, np.nan, 4, 5])

has_nan = np.any(np.isnan(a))

print(has_nan)

True


In [231]:
arr = np.array([[8, 4, 1],
                [5, 2, 7],
                [6, 9, 3]])

sorted_indices = arr[:,1].argsort()
sorted_arr = arr[sorted_indices]

print(sorted_arr)

[[5 2 7]
 [8 4 1]
 [6 9 3]]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
# flatten_arr = arr.flatten()
flatten_arr = arr.ravel() # returns a view instead
print(flatten_arr)

[1 2 3 4 5 6]


In [236]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_arr = np.vstack((a,b))
h_arr = np.hstack((a,b))
print("Vertical Stack: \n", v_arr)
print("Horizontal Stack: \n", h_arr)

Vertical Stack: 
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: 
 [1 2 3 4 5 6]


In [240]:
arr = np.arange(9)
split_arr = np.split(arr, 3)
print("Original Array:", arr)
print("Split Arrays:", split_arr)


Original Array: [0 1 2 3 4 5 6 7 8]
Split Arrays: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [244]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

# Add the two arrays
resultArray = arrayOne + arrayTwo

print("Result of array addition:")
print(resultArray)

# Square each element of the resultArray
squaredArray = resultArray ** 2

print("\nResult with each element squared:")
print(squaredArray)

Result of array addition:
[[20 39 33]
 [25 25 28]]

Result with each element squared:
[[ 400 1521 1089]
 [ 625  625  784]]


In [246]:
arr = np.array([[1, 2], [3, 4]])
inverted_arr = np.linalg.inv(arr)
print(inverted_arr)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [254]:
arr = np.array([5, 12, 29, 30, 44, 7, 18])
values = 30

mask = (arr < values)
print("Value : ", arr[mask])

Value :  [ 5 12 29  7 18]


In [258]:
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])
vals, counts = np.unique(arr,return_counts=True)
for v, c in zip(vals, counts):
  print(f"Value {v} occurs {c} time(s)")

Value 2 occurs 3 time(s)
Value 3 occurs 3 time(s)
Value 5 occurs 2 time(s)


In [265]:
a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

intersect = np.intersect1d(a, b)
union = np.union1d(a, b)

print("Intersection:",intersect)
print("Union:",union)

Intersection: [3 5 7]
Union: [1 2 3 4 5 6 7]


In [268]:
arr = np.array([[1, 2], [3, 4]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 3]
 [2 4]]


In [273]:
A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues (Scalars):", eigenvalues)
print("\nEigenvectors (Columns):\n", eigenvectors)

Eigenvalues (Scalars): [5. 2.]

Eigenvectors (Columns):
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [275]:
# 1. Box A: The coefficients (numbers in front of x and y)
A = np.array([[1, 2],
              [3, 4]])

# 2. Box B: The constant answers on the right side
B = np.array([8, 18])

# 3. Let NumPy do the heavy lifting
solution = np.linalg.solve(A, B)

print("Value of x:", solution[0])
print("Value of y:", solution[1])

Value of x: 1.9999999999999996
Value of y: 3.0


In [279]:
# 1. Create an 8x8 grid filled completely with zeros
arr = np.zeros((8,8), dtype=int)

# 2. Make the alternating squares equal to 1
arr[0::2, 1::2] = 1 # Even rows, odd columns
arr[1::2, 0::2] = 1 # Odd rows, even columns
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [283]:
arr = np.array([1.5, 2.8, 3.2, 4.1])
target_value = 3

# 1. Find the index of the closest number to 3
closest_idx = np.abs(arr-target_value).argmin()

# 2. Extract the actual value using that index
closest_value = arr[closest_idx]

print(f"The value closest to {target_value} is: {closest_value}")


The value closest to 3 is: 2.8


In [292]:
arr = np.array([1, 2, 3, 4, 5])

# Create an empty object array with the same size
obj_arr = np.empty(arr.size, dtype='object')

# Assign the elements from the original array
obj_arr[:] = arr

# We can now add a string element to it
obj_arr[1] = 'a'
print(obj_arr)
print(obj_arr.dtype)

[1 'a' 3 4 5]
object


In [295]:
arr = np.array([10, 20, 30, 100, 200, 300])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 110.0
Median: 65.0
Standard Deviation: 107.08252269472673
