## Numpy Array & Basics

Learning basics of numpy in `phase-1`

In [4]:
import numpy as np

### Creating array from list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: \n", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: \n", arr_2d)

1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### List VS Numpy array

In [11]:
py_list = [1,2,3]
print("Python list multiplication : \n", py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python array(numpy) multiplication : \n", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: \n", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2
print("\n Numpy operation time: \n", time.time() - start)

Python list multiplication : 
 [1, 2, 3, 1, 2, 3]
Python array(numpy) multiplication : 
 [2 4 6]

 List operation time: 
 0.7859089374542236

 Numpy Array operation time: 
 0.017843961715698242


### Creating array from scratch

In [14]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,11,2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.1173947  0.14943892 0.00874602]
 [0.46650425 0.87502057 0.92664149]]
sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrices & Tensor

In [16]:
vector = np.array([1,2,3])
print("Vector: \n", vector)

matrices = np.array([[1,2,3],
                   [4,5,6]])
print("Matrices: \n", matrices)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6], [7,8]]])
print("Matrices: \n", tensor)

Vector: 
 [1 2 3]
Matrices: 
 [[1 2 3]
 [4 5 6]]
Matrices: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


### Array Reshaping

In [24]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape((3,4))
print("Reshapes Array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array: \n", flattened)

# ravel (returns a view instead of copy)
raveled = reshaped.ravel()
print("Raveled Array: \n", raveled)

transpose = reshaped.T
print("Transposed Array: \n", transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshapes Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
